### ISSUE TITLE
npm install fails with error

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/blog#257]
The blog build is not working on my local machine (Mac).

@gdams @aahlenst any idea?

The last lines of the np install log file:

```
989 warn @pmmmwh/react-refresh-webpack-plugin@0.3.3 requires a peer of @types/webpack@^4.41.12 but none is installed. You must install peer dependencies yourself.
990 warn @pmmmwh/react-refresh-webpack-plugin@0.3.3 requires a peer of react-refresh@^0.8.2 but none is installed. You must install peer dependencies yourself.
991 warn @pmmmwh/react-refresh-webpack-plugin@0.3.3 requires a peer of sockjs-client@^1.4.0 but none is installed. You must install peer dependencies yourself.
992 warn @pmmmwh/react-refresh-webpack-plugin@0.3.3 requires a peer of type-fest@^0.13.1 but none is installed. You must install peer dependencies yourself.
993 warn @pmmmwh/react-refresh-webpack-plugin@0.3.3 requires a peer of webpack-plugin-serve@0.x || 1.x but none is installed. You must install peer dependencies yourself.
994 warn acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
995 warn gatsby-plugin-eslint@2.0.8 requires a peer of eslint-loader@^3.0.2 but none is installed. You must install peer dependencies yourself.
996 warn tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
997 warn ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
998 warn ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
999 verbose stack Error: sharp@0.25.2 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
999 verbose stack Exit status 1
999 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
999 verbose stack     at EventEmitter.emit (events.js:160:13)
999 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
999 verbose stack     at ChildProcess.emit (events.js:160:13)
999 verbose stack     at maybeClose (internal/child_process.js:943:16)
999 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
1000 verbose pkgid sharp@0.25.2
1001 verbose cwd /Users/hendrikebbers/git/AdoptOpenJDK-blog
1002 verbose Darwin 19.5.0
1003 verbose argv "/usr/local/Cellar/node/9.5.0/bin/node" "/usr/local/bin/npm" "install"
1004 verbose node v9.5.0
1005 verbose npm  v5.6.0
1006 error code ELIFECYCLE
1007 error errno 1
1008 error sharp@0.25.2 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
1008 error Exit status 1
1009 error Failed at the sharp@0.25.2 install script.
1009 error This is probably not a problem with npm. There is likely additional logging output above.
1010 verbose exit [ 1, true ]
```

**Comment by aahlenst** [comment]
I suspect Node 9.5.0 is too old. 10 is the oldest maintained version.

**Comment by hendrikebbers** [comment]
yes, npm update solved the issue
